<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>todo</string>
	</array>
	<key>foldingStartMarker</key>
	<string>^[A-Z].+$</string>
	<key>foldingStopMarker</key>
	<string>^\s*$</string>
	<key>name</key>
	<string>TODO List</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>todo.category.name</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>todo.category.extras</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^\s*([A-Z].+)\s+\-\s+(.+)$</string>
			<key>name</key>
			<string>todo.category</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^\s*([A-Z].+)$</string>
			<key>name</key>
			<string>todo.category.name</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^\s*\-\s+.+$</string>
			<key>name</key>
			<string>todo.task.incomplete</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^\s*x\s+.+$</string>
			<key>name</key>
			<string>todo.task.complete</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^\s*\+\s+.+$</string>
			<key>name</key>
			<string>todo.task.dormant</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^\s*\?\s+.+$</string>
			<key>name</key>
			<string>todo.task.question</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^\s*\%\s+.+$</string>
			<key>name</key>
			<string>todo.task.large</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^\s*\!\s+.+$</string>
			<key>name</key>
			<string>todo.task.urgent</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>text.todo</string>
	<key>uuid</key>
	<string>86DA9302-C76C-49A7-9B01-9ADE54CC24F2</string>
</dict>
</plist>
